baseURL = "https://jackorcherton.github.io/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Jack Orcherton"
theme = "HackIt"
enableGitInfo = true
enableRobotsTXT = true

[params]
  version = "0.2.X"
  description = "The personal site for Jack Orcherton"
  keywords = ["Jack", "Orcherton", "Jack Orcherton", "cybersecurity", "Ethical Hacking", "CV"]
  defaultTheme = "dark"
  gitRepo = "https://github.com/jackorcherton/jackorcherton.github.io"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 3

[params.cookieconsent]
  enable = false

[params.search]
  enable = true
  type = "lunr"
  contentLength = 4000
  placeholder = ""
  maxResultLength = 10
  snippetLength = 30
  highlightTag = "em"
  absoluteURL = false

[params.page]
  linkToMarkdown = true
  hiddenFromSearch = false

[params.footer]
  hugo = false
  since = 2021

[params.home.profile]
  gravatarEmail = "jackorcherton@outlook.com"
  avatarAlt = "Jack Orcherton"
  title = "Jack Orcherton"
  subtitle = "Cybersecurity and Ethical Hacking Student, plus Overall Tech Enthusiast"
  disclaimer = "Content on this website will teach hacking, you are responsible to ensure that it is used ethically and all laws are followed"
  typeit = true

[params.social]
  GitHub = "jackorcherton"
  Linkedin = "jack-orcherton"
  Twitter = "JackOrcherton"
  Instagram = "jackorcherton"
  Facebook = "jackorcherton"
  Telegram = "JackOrcherton"
  RSS = true 

[author]
  name = "Jack Orcherton"

[markup]
  [markup.highlight]
    # required
    noClasses = false
